# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Nico-Admin/Documents/ENSEIRB/Travail/S8/Projet_MP3/ProjetMP3/ProjetMP3.cache/wt [current_project]
set_property parent.project_path C:/Users/Nico-Admin/Documents/ENSEIRB/Travail/S8/Projet_MP3/ProjetMP3/ProjetMP3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_cache_permissions disable [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Nico-Admin/Documents/ENSEIRB/Travail/S8/Projet_MP3/Design/PWM.vhd
  C:/Users/Nico-Admin/Documents/ENSEIRB/Travail/S8/Projet_MP3/Design/Reg_Button.vhd
  C:/Users/Nico-Admin/Documents/ENSEIRB/Travail/S8/Projet_MP3/Design/Volume_Manager.vhd
  C:/Users/Nico-Admin/Documents/ENSEIRB/Travail/S8/Projet_MP3/Design/cpt_1_599.vhd
  C:/Users/Nico-Admin/Documents/ENSEIRB/Travail/S8/Projet_MP3/Design/cpt_1_9.vhd
  C:/Users/Nico-Admin/Documents/ENSEIRB/Travail/S8/Projet_MP3/Design/cpt_adresse.vhd
  C:/Users/Nico-Admin/Documents/ENSEIRB/Travail/S8/Projet_MP3/Design/cpt_timebase.vhd
  C:/Users/Nico-Admin/Documents/ENSEIRB/Travail/S8/Projet_MP3/Design/fsm.vhd
  C:/Users/Nico-Admin/Documents/ENSEIRB/Travail/S8/Projet_MP3/Design/uart_recv.vhd
  C:/Users/Nico-Admin/Documents/ENSEIRB/Travail/S8/Projet_MP3/Design/merger_8b_to_16b.vhd
  C:/Users/Nico-Admin/Documents/ENSEIRB/Travail/S8/Projet_MP3/Design/stop_counter.vhd
  C:/Users/Nico-Admin/Documents/ENSEIRB/Travail/S8/Projet_MP3/Design/full_uart_recv.vhd
  C:/Users/Nico-Admin/Documents/ENSEIRB/Travail/S8/Projet_MP3/Design/gen_audio.vhd
  C:/Users/Nico-Admin/Documents/ENSEIRB/Travail/S8/Projet_MP3/Design/gestion_freq.vhd
  C:/Users/Nico-Admin/Documents/ENSEIRB/Travail/S8/Projet_MP3/Design/mod8.vhd
  C:/Users/Nico-Admin/Documents/ENSEIRB/Travail/S8/Projet_MP3/Design/mux8.vhd
  C:/Users/Nico-Admin/Documents/ENSEIRB/Travail/S8/Projet_MP3/Design/ram.vhd
  C:/Users/Nico-Admin/Documents/ENSEIRB/Travail/S8/Projet_MP3/Design/top_level_part1.vhd
  C:/Users/Nico-Admin/Documents/ENSEIRB/Travail/S8/Projet_MP3/Design/top_level_part2.vhd
  C:/Users/Nico-Admin/Documents/ENSEIRB/Travail/S8/Projet_MP3/Design/transcodeur.vhd
  C:/Users/Nico-Admin/Documents/ENSEIRB/Travail/S8/Projet_MP3/Design/MP3_top_level.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Nico-Admin/Documents/ENSEIRB/Travail/S8/Projet_MP3/Design/Nexys4.xdc
set_property used_in_implementation false [get_files C:/Users/Nico-Admin/Documents/ENSEIRB/Travail/S8/Projet_MP3/Design/Nexys4.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top MP3_top_level -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MP3_top_level.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MP3_top_level_utilization_synth.rpt -pb MP3_top_level_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
